version: 2
models:
- name: channels_dim
  description: Dimension table for sales channels, containing basic channel identifiers and names.
  columns:
  - name: channelId
    description: Unique identifier for each channel
    tests:
    - not_null
    - unique
  - name: channelName
    description: Name of the sales channel

- name: geography_dim
  description: Geographical dimension table including types, countries, and continents.
  columns:
  - name: geographyKey
    description: Unique identifier for each geography
    tests:
    - not_null
    - unique
  - name: geographyType
    description: Type of the geography, such as urban or rural
  - name: continentName
    description: Continent where the geography is located
  - name: country
    description: Country name within the geography

- name: products_dim
  description: Product dimension table filtered by products that have recorded sales.
  columns:
  - name: productKey
    description: Unique identifier for the product
    tests:
    - not_null
    - unique
  - name: productName
    description: Name of the product
  - name: productDesc
    description: Description of the product
  - name: productCategory
    description: Main product category
  - name: productSubcategory
    description: Subcategory under the product category
  - name: brandName
    description: Brand associated with the product
  - name: className
    description: Class name grouping for the product
  - name: manufacturer
    description: Manufacturer of the product

- name: promotions_dim
  description: Dimension table for promotions, including period and discount details.
  columns:
  - name: promotionKey
    description: Unique identifier for the promotion
    tests:
    - not_null
    - unique
  - name: promotionName
    description: Name of the promotion
  - name: discountPercent
    description: Discount percentage offered in the promotion
  - name: startDate
    description: Promotion start date
  - name: endDate
    description: Promotion end date

- name: sales_fact
  description: Fact table recording all product sales transactions.
  columns:
  - name: sales_key
    description: Primary key for each sales record
    tests:
    - not_null
    - unique
  - name: transaction_date
    description: Date of transaction
  - name: product_key
    description: Foreign key referencing the product
    tests:
    - relationships:
        to: products_dim
        field: productKey
  - name: channel_key
    description: Foreign key referencing the sales channel
    tests:
    - relationships:
        to: channels_dim
        field: channelId
  - name: store_key
    description: Foreign key referencing the store
    tests:
    - relationships:
        to: stores_dim
        field: storeKey
  - name: promotion_key
    description: Foreign key referencing the promotion
    tests:
    - relationships:
        to: promotions_dim
        field: promotionKey
  - name: geography_key
    description: Foreign key referencing the geography
    tests:
    - relationships:
        to: geography_dim
        field: geographyKey
  - name: gross_quantity
    description: Quantity of items sold before returns and discounts
  - name: net_quantity
    description: Net quantity sold after accounting for returns and discounts
  - name: net_cost_amount
    description: Total cost for the net quantity sold
  - name: net_sales_amount
    description: Total revenue for the net quantity sold

- name: stores_dim
  description: Store dimension table with store attributes and location details.
  columns:
  - name: storeKey
    description: Unique identifier for the store
    tests:
    - not_null
    - unique
  - name: storeType
    description: Type/category of the store
  - name: storeName
    description: Name of the store
  - name: country
    description: Country where the store is located
  - name: status
    description: Current status of the store (open/closed)
  - name: closeReason
    description: Reason for store closure, if applicable
  - name: NumberOfEmployee
    description: Total number of employees at the store
  - name: sellingAreaSize
    description: Size of the store's selling area in square meters