name: Deploy dbt to Prod

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      PG_HOST: ${{ secrets.PG_PROD_HOST }}
      PG_PORT: ${{ secrets.PG_PROD_PORT }}
      PG_USER: ${{ secrets.PG_PROD_USER }}
      PG_PASSWORD: ${{ secrets.PG_PROD_PASSWORD }}
      PG_DBNAME: ${{ secrets.PG_PROD_DBNAME }}
      PG_SCHEMA: ${{ secrets.PG_PROD_SCHEMA }}
      DBT_PROFILES_DIR: ${{ github.workspace }}/.dbt

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('elt_trans/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: elt_trans

      - name: Run dbt (prod)
        run: |
          dbt debug --target prod
          dbt run --target prod
          dbt test --target prod
        working-directory: elt_trans